import { CadConversionService } from './cad-conversion.service';
import { ConversionPipelineService } from './conversion-pipeline.service';
import type { Response } from 'express';
export declare class CadConversionController {
    private readonly cadConversionService;
    private readonly conversionPipeline;
    constructor(cadConversionService: CadConversionService, conversionPipeline: ConversionPipelineService);
    uploadFile(file: Express.Multer.File): Promise<{
        status: string;
        id: number;
        createdAt: Date;
        updatedAt: Date;
        fileSize: number | null;
        originalFileName: string;
        originalFilePath: string;
        svgFilePath: string | null;
        cadVersion: string | null;
        conversionTime: number | null;
        entityCount: number | null;
        layerCount: number | null;
        blockCount: number | null;
        errorMessage: string | null;
    }>;
    findAll(): Promise<{
        status: string;
        id: number;
        createdAt: Date;
        updatedAt: Date;
        fileSize: number | null;
        originalFileName: string;
        originalFilePath: string;
        svgFilePath: string | null;
        cadVersion: string | null;
        conversionTime: number | null;
        entityCount: number | null;
        layerCount: number | null;
        blockCount: number | null;
        errorMessage: string | null;
    }[]>;
    findOne(id: string): Promise<{
        status: string;
        id: number;
        createdAt: Date;
        updatedAt: Date;
        fileSize: number | null;
        originalFileName: string;
        originalFilePath: string;
        svgFilePath: string | null;
        cadVersion: string | null;
        conversionTime: number | null;
        entityCount: number | null;
        layerCount: number | null;
        blockCount: number | null;
        errorMessage: string | null;
    }>;
    getSvg(id: string, res: Response): Promise<void>;
    remove(id: string): Promise<{
        status: string;
        id: number;
        createdAt: Date;
        updatedAt: Date;
        fileSize: number | null;
        originalFileName: string;
        originalFilePath: string;
        svgFilePath: string | null;
        cadVersion: string | null;
        conversionTime: number | null;
        entityCount: number | null;
        layerCount: number | null;
        blockCount: number | null;
        errorMessage: string | null;
    }>;
}
