import { Injectable, Logger } from '@nestjs/common';
import { CadConversionService } from './cad-conversion.service';
import { CadConfigService } from './cad-config.service';
import * as fs from 'fs';
import * as path from 'path';
// @ts-ignore
import DxfParser from 'dxf-parser';

@Injectable()
export class ConversionPipelineService {
  private readonly logger = new Logger(ConversionPipelineService.name);

  constructor(
    private readonly cadConversionService: CadConversionService,
    private readonly cadConfig: CadConfigService
  ) {}

  async runPipeline(conversionId: number, filePath: string, originalName: string) {
    const startTime = Date.now();
    try {
      await this.cadConversionService.update(conversionId, { status: 'PROCESSING' });
      this.logger.log(`Starting pipeline for ${originalName} (ID: ${conversionId})`);

      const ext = path.extname(originalName).toLowerCase();
      let workingFilePath = filePath;

      // 1. Convert DWG to DXF if required
      if (ext === '.dwg') {
        this.logger.log(`Converting DWG to DXF for ${originalName}`);
        
        const odaPath = this.cadConfig.odaConverterPath;
        if (!odaPath || !fs.existsSync(odaPath)) {
          throw new Error('ODA File Converter is not installed or ODA_CONVERTER_PATH is invalid.');
        }

        const tempDir = this.cadConfig.tempDirectory;
        const outDir = this.cadConfig.outputDirectory;

        const tempIn = path.join(tempDir, `in_${conversionId}`);
        const tempOut = path.join(tempDir, `out_${conversionId}`);

        fs.mkdirSync(tempIn, { recursive: true });
        fs.mkdirSync(tempOut, { recursive: true });

        // Copy file to temp input directory
        const tempFilePath = path.join(tempIn, originalName);
        fs.copyFileSync(filePath, tempFilePath);

        const { execSync } = require('child_process');
        
        try {
           // Syntax: ODAFileConverter <InputFolder> <OutputFolder> <Version> <OutputFormat> <Recurse> <Audit>
           execSync(`"${odaPath}" "${tempIn}" "${tempOut}" "ACAD2018" "DXF" "0" "1"`, { stdio: 'ignore' });
        } catch (error) {
           throw new Error(`ODA File Converter failed: ${error.message}`);
        }

        // Find the generated DXF file in the output directory
        const outFiles = fs.readdirSync(tempOut);
        const dxfFile = outFiles.find(f => f.toLowerCase().endsWith('.dxf'));
        if (!dxfFile) {
          throw new Error('DXF file was not generated by the converter.');
        }

        workingFilePath = path.join(outDir, `${path.basename(originalName, '.dwg')}_${conversionId}.dxf`);
        fs.copyFileSync(path.join(tempOut, dxfFile), workingFilePath);

        // Cleanup temp directories
        fs.rmSync(tempIn, { recursive: true, force: true });
        fs.rmSync(tempOut, { recursive: true, force: true });
        
        this.logger.log(`DWG converted to DXF successfully: ${workingFilePath}`);
      }

      // 2. Read DXF
      const fileContent = fs.readFileSync(workingFilePath, 'utf-8');
      
      // 3. Parse DXF
      const parser = new DxfParser();
      let parsedData;
      try {
        parsedData = parser.parseSync(fileContent);
      } catch (err) {
        throw new Error(`Failed to parse DXF: ${err.message}`);
      }

      if (!parsedData || !parsedData.entities) {
        throw new Error('Invalid or empty DXF file.');
      }

      // 4. Generate SVG
      const svgPath = filePath + '.svg';
      const svgContent = this.generateSvgFromDxf(parsedData);
      fs.writeFileSync(svgPath, svgContent);

      // 5. Extract metadata
      const entityCount = parsedData.entities.length;
      const layerCount = parsedData.tables && parsedData.tables.layer && parsedData.tables.layer.layers ? Object.keys(parsedData.tables.layer.layers).length : 0;
      const blockCount = parsedData.blocks ? Object.keys(parsedData.blocks).length : 0;

      // 6. Complete
      const conversionTime = Date.now() - startTime;
      await this.cadConversionService.update(conversionId, {
        status: 'SUCCESS',
        svgFilePath: svgPath,
        entityCount,
        layerCount,
        blockCount,
        conversionTime,
        cadVersion: parsedData.header && parsedData.header.$ACADVER ? parsedData.header.$ACADVER : 'Unknown'
      });
      
      this.logger.log(`Pipeline successful for ${originalName}`);
    } catch (error) {
      this.logger.error(`Pipeline failed for ${originalName}: ${error.message}`);
      await this.cadConversionService.update(conversionId, {
        status: 'FAILED',
        errorMessage: error.message,
        conversionTime: Date.now() - startTime
      });
    }
  }

  private generateSvgFromDxf(data: any): string {
    const renderer = new CadSvgRenderer(data);
    const result = renderer.render();
    this.logger.log(`SVG Generation stats: Converted ${result.stats.converted}, Skipped ${result.stats.skipped}. Skipped types: ${result.stats.skippedTypes.join(', ')}`);
    return result.svg;
  }
}




export class CadSvgRenderer {
  private minX = Infinity;
  private minY = Infinity;
  private maxX = -Infinity;
  private maxY = -Infinity;
  private paths: string[] = [];
  private defs: string[] = [];
  
  private convertedCount = 0;
  private skippedCount = 0;
  private skippedTypes = new Set<string>();

  // Standard AutoCAD Color Index (ACI) to Hex mapping (0-255)
  // Simplified for performance. Fallback to currentColor.
  private aciColors: Record<number, string> = {
    1: '#FF0000', 2: '#FFFF00', 3: '#00FF00', 4: '#00FFFF', 5: '#0000FF',
    6: '#FF00FF', 7: '#000000', 8: '#808080', 9: '#C0C0C0'
  };

  constructor(private data: any) {}

  public render(): { svg: string, stats: any } {
    this.processBlocks();
    this.processEntities(this.data.entities || []);

    if (this.minX === Infinity) {
      this.minX = 0; this.minY = 0; this.maxX = 100; this.maxY = 100;
    }

    const width = this.maxX - this.minX;
    const height = Math.abs(this.maxY - this.minY);
    const padding = Math.max(width, height) * 0.05 || 10;

    const viewBox = `${this.minX - padding} ${-this.maxY - padding} ${width + padding * 2} ${height + padding * 2}`;
    const strokeW = Math.max(width, height) * 0.001 || 0.5;

    const defsBlock = this.defs.length > 0 ? `<defs>\n${this.defs.join('\n')}\n</defs>` : '';

    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="100%" height="100%">
      ${defsBlock}
      <g stroke-linecap="round" stroke-linejoin="round" stroke="currentColor" stroke-width="${strokeW}">
        ${this.paths.join('\n        ')}
      </g>
    </svg>`;

    return {
      svg,
      stats: {
        converted: this.convertedCount,
        skipped: this.skippedCount,
        skippedTypes: Array.from(this.skippedTypes)
      }
    };
  }

  private addBounds(x: number, y: number) {
    if (x < this.minX) this.minX = x;
    if (x > this.maxX) this.maxX = x;
    if (y < this.minY) this.minY = y;
    if (y > this.maxY) this.maxY = y;
  }

  private getColor(entity: any): string {
    if (entity.colorNumber && this.aciColors[entity.colorNumber]) {
      return this.aciColors[entity.colorNumber];
    }
    return 'currentColor';
  }

  private getBulgeArc(x1: number, y1: number, x2: number, y2: number, bulge: number) {
    if (!bulge || bulge === 0) return `L ${x2} ${y2}`;
    const dx = x2 - x1;
    const dy = y2 - y1;
    const d = Math.sqrt(dx * dx + dy * dy);
    if (d === 0) return `L ${x2} ${y2}`;
    
    const theta = 4 * Math.atan(bulge);
    const r = Math.abs(d / (2 * Math.sin(theta / 2)));
    
    const largeArcFlag = Math.abs(bulge) > 1 ? 1 : 0;
    const sweepFlag = bulge > 0 ? 0 : 1;
    
    return `A ${r} ${r} 0 ${largeArcFlag} ${sweepFlag} ${x2} ${y2}`;
  }

  private processBlocks() {
    if (!this.data.blocks) return;
    
    for (const [blockName, block] of Object.entries(this.data.blocks)) {
      if (!block || !(block as any).entities) continue;
      
      const originalPaths = this.paths;
      this.paths = [];
      this.processEntities((block as any).entities, false); // Don't track bounds for block defs
      
      if (this.paths.length > 0) {
        this.defs.push(`<g id="block_${this.sanitizeId(blockName)}">${this.paths.join('\n')}</g>`);
      }
      this.paths = originalPaths;
    }
  }

  private sanitizeId(id: string): string {
    return id.replace(/[^a-zA-Z0-9_-]/g, '_');
  }

  private processEntities(entities: any[], trackBounds = true) {
    for (const entity of entities) {
      const color = this.getColor(entity);
      const strokeStr = color !== 'currentColor' ? `stroke="${color}"` : '';
      const bgAttr = `data-cad-type="background"`;
      const combinedAttrs = strokeStr ? `${bgAttr} ${strokeStr}` : bgAttr;

      try {
        if (entity.type === 'LINE') {
          const x1 = entity.vertices[0].x, y1 = entity.vertices[0].y;
          const x2 = entity.vertices[1].x, y2 = entity.vertices[1].y;
          if (trackBounds) { this.addBounds(x1, y1); this.addBounds(x2, y2); }
          this.paths.push(`<line x1="${x1}" y1="${-y1}" x2="${x2}" y2="${-y2}" ${combinedAttrs} />`);
          this.convertedCount++;

        } else if (entity.type === 'LWPOLYLINE' || entity.type === 'POLYLINE') {
          if (!entity.vertices || entity.vertices.length < 2) continue;
          let d = `M ${entity.vertices[0].x} ${-entity.vertices[0].y}`;
          if (trackBounds) this.addBounds(entity.vertices[0].x, entity.vertices[0].y);
          
          for (let i = 0; i < entity.vertices.length - 1; i++) {
            const v1 = entity.vertices[i];
            const v2 = entity.vertices[i+1];
            if (trackBounds) this.addBounds(v2.x, v2.y);
            d += ' ' + this.getBulgeArc(v1.x, -v1.y, v2.x, -v2.y, v1.bulge);
          }
          
          if (entity.shape || entity.closed) {
            const vLast = entity.vertices[entity.vertices.length - 1];
            const vFirst = entity.vertices[0];
            d += ' ' + this.getBulgeArc(vLast.x, -vLast.y, vFirst.x, -vFirst.y, vLast.bulge);
            d += ' Z';
          }
          this.paths.push(`<path d="${d}" fill="none" ${combinedAttrs} />`);
          this.convertedCount++;

        } else if (entity.type === 'ARC') {
          const cx = entity.center.x, cy = entity.center.y, r = entity.radius;
          const startAngle = entity.startAngle, endAngle = entity.endAngle;
          
          if (trackBounds) { this.addBounds(cx - r, cy - r); this.addBounds(cx + r, cy + r); }
          
          const x1 = cx + r * Math.cos(startAngle);
          const y1 = -cy - r * Math.sin(startAngle);
          const x2 = cx + r * Math.cos(endAngle);
          const y2 = -cy - r * Math.sin(endAngle);
          
          let sweepAngle = (endAngle - startAngle + Math.PI * 2) % (Math.PI * 2);
          if (sweepAngle === 0) sweepAngle = Math.PI * 2;
          
          const largeArcFlag = sweepAngle > Math.PI ? 1 : 0;
          const sweepFlag = 0;
          this.paths.push(`<path d="M ${x1} ${y1} A ${r} ${r} 0 ${largeArcFlag} ${sweepFlag} ${x2} ${y2}" fill="none" ${combinedAttrs} />`);
          this.convertedCount++;

        } else if (entity.type === 'CIRCLE') {
          const cx = entity.center.x, cy = -entity.center.y, r = entity.radius;
          if (trackBounds) { this.addBounds(entity.center.x - r, entity.center.y - r); this.addBounds(entity.center.x + r, entity.center.y + r); }
          this.paths.push(`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" ${combinedAttrs} />`);
          this.convertedCount++;

        } else if (entity.type === 'ELLIPSE') {
          const cx = entity.center.x, cy = -entity.center.y;
          const mx = entity.majorAxisEndPoint.x, my = entity.majorAxisEndPoint.y;
          const rx = Math.sqrt(mx * mx + my * my);
          const ry = rx * entity.axisRatio;
          
          if (trackBounds) { this.addBounds(entity.center.x - rx, entity.center.y - rx); this.addBounds(entity.center.x + rx, entity.center.y + rx); }
          
          // DXF Ellipse can be rotated. Angle = atan2(my, mx)
          const angle = Math.atan2(my, mx) * (180 / Math.PI);
          // SVG ellipse
          this.paths.push(`<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" transform="rotate(${-angle} ${cx} ${cy})" fill="none" ${combinedAttrs} />`);
          this.convertedCount++;

        } else if (entity.type === 'SPLINE') {
          // Simplistic spline conversion: treat control points as polyline (bezier conversion is too complex for basic renderer without library)
          if (!entity.controlPoints || entity.controlPoints.length < 2) continue;
          let d = `M ${entity.controlPoints[0].x} ${-entity.controlPoints[0].y}`;
          if (trackBounds) this.addBounds(entity.controlPoints[0].x, entity.controlPoints[0].y);
          
          for (let i = 1; i < entity.controlPoints.length; i++) {
            const pt = entity.controlPoints[i];
            if (trackBounds) this.addBounds(pt.x, pt.y);
            d += ` L ${pt.x} ${-pt.y}`;
          }
          this.paths.push(`<path d="${d}" fill="none" ${combinedAttrs} opacity="0.8" stroke-dasharray="2 2" />`); // dashed to show it's approximated
          this.convertedCount++;

        } else if (entity.type === 'MTEXT' || entity.type === 'TEXT') {
          let text = (entity.text || '').replace(/\\P/g, ' ').replace(/\\[A-Za-z0-9]+;/g, '').replace(/\{.*?\}/g, '').trim();
          if (!text) continue;
          
          text = text.replace(/\\[fF][^;]+;/g, '').replace(/[{}]/g, '');
          
          let x = 0, y = 0;
          if (entity.position) {
            x = entity.position.x; y = -entity.position.y;
            if (trackBounds) this.addBounds(entity.position.x, entity.position.y);
          }
          const h = entity.height || 1;
          
          let rot = 0;
          if (entity.directionVector) {
            rot = Math.atan2(-entity.directionVector.y, entity.directionVector.x) * (180 / Math.PI);
          } else if (entity.rotation !== undefined) {
            rot = -entity.rotation;
          }
          const fillStr = color !== 'currentColor' ? `fill="${color}"` : 'fill="currentColor"';
          this.paths.push(`<text x="${x}" y="${y}" font-size="${h}" font-family="sans-serif" transform="rotate(${rot} ${x} ${y})" ${fillStr} stroke="none" alignment-baseline="middle" text-anchor="middle" data-cad-type="background">${text}</text>`);
          this.convertedCount++;

        } else if (entity.type === 'INSERT') {
          const blockName = this.sanitizeId(entity.name);
          let x = 0, y = 0;
          if (entity.position) {
            x = entity.position.x;
            y = -entity.position.y;
            if (trackBounds) this.addBounds(entity.position.x, entity.position.y); // highly approximated bounds
          }
          
          let scaleX = entity.scaleX || 1;
          let scaleY = entity.scaleY || 1;
          let rot = entity.rotation !== undefined ? -entity.rotation : 0;
          
          const transform = `translate(${x} ${y}) rotate(${rot}) scale(${scaleX} ${scaleY})`;
          this.paths.push(`<use href="#block_${blockName}" transform="${transform}" />`);
          this.convertedCount++;

        } else {
          this.skippedCount++;
          this.skippedTypes.add(entity.type);
        }
      } catch (err) {
        this.skippedCount++;
        this.skippedTypes.add(entity.type + '_ERROR');
      }
    }
  }
}
